name: Dependency Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  dependency_check:
    name: Check for Dependency Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Check and Tidy Dependencies
        run: |
          go get -u -v
          go mod tidy
